export const ModifierId = Object.freeze({
  MULTIPLIER_2X: 'MULTIPLIER_2X',
  MULTIPLIER_3X: 'MULTIPLIER_3X',
  BONUS_FLAT:    'BONUS_FLAT',
  SCORE_DOUBLE:  'SCORE_DOUBLE',
  GHOST_SHIELD:  'GHOST_SHIELD',
  SLOW_TIME:     'SLOW_TIME',
});
